In [ ]:
import os
print(os.listdir('/content'))

['.config', 'Sample - Superstore.xls', 'sample_data']

In [1]:
import os
print(os.listdir())

['.config', 'sample_data']

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Sample - Superstore.xls to Sample - Superstore.xls

In [3]:
import os
print(os.listdir())

['.config', 'Sample - Superstore.xls', 'sample_data']

In [4]:
import pandas as pd

df = pd.read_excel("Sample - Superstore.xls")

df.head()

     Unnamed: 0    Unnamed: 1
0           NaN           NaN
1  Sum of Sales         Total
2         Total  2297200.8603

In [5]:
import pandas as pd

xls = pd.ExcelFile("Sample - Superstore.xls")

print(xls.sheet_names)

['Sheet1', 'Sheet2', 'Sheet3', 'Sheet4', 'Dashboard', 'Sheet5', 'Orders', 'Returns', 'People']

In [6]:
import pandas as pd

df = pd.read_excel("Sample - Superstore.xls", sheet_name="Orders")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.shape

(9994, 21)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [9]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.to_csv("Cleaned_Superstore.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [14]:
from google.colab import files

files.download("Cleaned_Superstore.csv")

In [ ]:
import pandas as pd

df = pd.read_excel('/content/Sample - Superstore.xls')

df.head()

     Unnamed: 0    Unnamed: 1
0           NaN           NaN
1  Sum of Sales         Total
2         Total  2297200.8603

In [ ]:
import pandas as pd

xls = pd.ExcelFile('/content/Sample - Superstore.xls')

print(xls.sheet_names)

['Sheet1', 'Sheet2', 'Sheet3', 'Sheet4', 'Dashboard', 'Sheet5', 'Orders', 'Returns', 'People']

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

MessageError: Error: credential propagation was unsuccessful

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1xqoM8_N17F4RXOHV0PaBTefIA6Db0WkRBUCqIoDpck8/edit#gid=0